### ISSUE TITLE
0.4.0 Meta Issue

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1030]
This is a meta issue for 0.4.0

There are a lot of features that have not yet been ported to the 0.4 branch. Instead of tracking individually, we will track these in a meta-issue. Here are just a few and I'm sure more will be added:

* [x] migrate Gitlab to 0.4
* [ ] migrate Bitbucket to 0.4
* [ ] yaml condition should include `on_success` and `on_failure` for notification plugins
* [x] load config from env vars (as opposed to toml) using new `pkg/config` [pull request #1032]
* [ ] re-enable multiple Docker nodes in the yaml. Currently accepts a `string`. Change to `[]string`

And some bugs / features that need to be worked out:

* [x] cancel a build leaves behind artifacts. The drone-build container should trap the kill event and perform cleanup before it shuts down
* [x] cancel build behavior needs to change. We should be able to cancel a pending (in queue) build including all matrix builds. Once a build is started, however, we should only be able to cancel each individual matrix build. There are technical reasons for this. I can explain
* [x] build timeout should be moved to the `drone-build` container instead of inside the Drone web app
* [ ] verify plugin white-list works
* [ ] verify global environment variables work

And some UI stuff:

* [x] finish styling the build page
* [x] if only a single build (ie no build matrix) should immediately display build output

And document the following:

* [x] document api via swagger spec at `doc/swagger.json`
* [x] document how to install and setup 0.4
* [x] document how to configure build yaml in 0.4

In addition, the following plugins need to be migrated to the new plugin model. Note that we will not hold up the `0.4` release on the account of plugins, since they can be added at any time without any changes to the core Drone codebase:

* [ ] Email plugin at `drone-plugins/drone-email`
* [ ] Hipchat plugin at `drone-plugins/drone-hipchat`
* [ ] Heroku plugin using [hk](https://github.com/heroku/hk) at `drone-plugins/drone-heroku`
* [x] Git Push plugin at `drone-plugins/drone-git-push`
* [ ] Rsync Deploy plugin at `drone-plugins/drone-rsync`
* [ ] Flowdock plugin at `drone-plugins/drone-flowdock`
* [ ] NPM plugin at `drone-plugins/drone-npm`
* [ ] Pypi plugin at `drone-plugins/drone-pypi`
* [ ] Bintray plugin at `drone-plugins/drone-bintray`
* [ ] GitHub release plugin at `drone-plugins/drone-github-release`

**Comment by JeanMertz** [comment]
not sure if I should post this here or in a new issue, but:

Using Drone 0.4 with GH, I can see the following happening in a PR to which I force-pushed:

```
[GIN] 2015/06/08 - 05:45:06 | 200 |  411.092286ms | 192.30.252.42:33734 |   POST    /api/hook
time="2015-06-08T05:45:06Z" level=error msg="failure to save commit for myOrg/myRepo. meddler.Insert: DB error in QueryRow: pq: duplicate key value violates unique constraint \"commits_repo_id_commit_sha_commit_ref_key\"" 
[GIN] 2015/06/08 - 05:45:06 | 500 |  489.139687ms | 192.30.252.45:42425 |   POST    /api/hook
Error #01: meddler.Insert: DB error in QueryRow: pq: duplicate key value violates unique constraint "commits_repo_id_commit_sha_commit_ref_key"
     Meta: Operation aborted
```


The first one (`200 Ok`) received the following from GH:

```
Request URL: http://ci.myOrg/api/hook?access_token=xxx
Request method: POST
content-type: application/x-www-form-urlencoded
Expect: 
User-Agent: GitHub-Hookshot/96ce10d
X-GitHub-Delivery: xxx
X-GitHub-Event: push
```

The failed one had event `X-GitHub-Event: pull_request`

**Comment by bradrydzewski** [comment]
pushed e935bed53eee1f8c7dc4e94d7e8c8e855254d418 to fix. There was a unique constraint on the `sha` and `ref` that was no longer necessary.

> not sure if I should post this here or in a new issue, but:

yep, let's keep the issues and dialoge here for now. thanks!

**Comment by JeanMertz** [comment]
Awesome :+1:. That also fixed the missing build status.

**Comment by JeanMertz** [comment]
When merging a PR, drone tries to build the PR again.

This often fails, because the "merge" button changes to a "delete branch" button on GH and we instantly hit this button because the branch is no longer needed.

**Comment by JeanMertz** [comment]
Also: It doesn't look like Drone updates the master branch status after a merge. The master branch has no CI status indicator in the branch overview screen on GH. The build on master after the PR merge did finish as expected.

**Comment by bradrydzewski** [comment]
>  It doesn't look like Drone updates the master branch status after a merge.

We were only updating status for pull requests. Fixed in commit 13a05a0106a92a4bbed388169f1be5eb112f74b3

> When merging a PR, drone tries to build the PR again.

Would you be able to get me the `action` value in the json payload that is being sent for that PR? We currently ignore when `hook.Action != "opened" && hook.Action != "synchronize"`, however, it sounds like there may be a `deleted` status or something that needs to be ignored as well.

**Comment by JeanMertz** [comment]
> Would you be able to get me the action value in the json payload that is being sent for that PR? We currently ignore when hook.Action != "opened" && hook.Action != "synchronize", however, it sounds like there may be a deleted status or something that needs to be ignored as well.

Here's the (sanitized) payload: https://gist.github.com/JeanMertz/ec4670ed496b89aadbf0

**Comment by tboerger** [comment]
slack/let's chat/mattermost notification is missing in the list :)

**Comment by bradrydzewski** [comment]
all check list items are now issues, so closing this
